export const ActionTypes = {
    SIGNUP_USER: "SIGNUP_USER",
    ADD_USER: "ADD_USER",
    SET_USER:"SET_USER",
    SET_INVALID_USERS:"SET_INVALID_USERS",
    REGISTER_USER:"REGISTER_USER",
    DECLINE_USER:"DECLINE_USER",
    SET_PRODUCTS:"SET_PRODUCTS",
    SET_STATIONERY:"SET_STATIONERY",
    SET_NOTES:"SET_NOTES",
    SET_ENOTES:"SET_ENOTES",
    SET_PREVIOUS_PAPERS:"SET_PREVIOUS_PAPERS",
    SET_MY_PRODUCTS:"SET_MY_PRODUCTS",   //Unrequired
    

    SET_ALL_PRODUCTS_BUTTON:"SET_ALL_PRODUCTS_BUTTON",
    SET_STATIONERY_BUTTON:"SET_STATIONERY_BUTTON",
    SET_NOTES_BUTTON:"SET_NOTES_BUTTON",
    SET_ENOTES_BUTTON:"SET_ENOTES_BUTTON",
    SET_PREVIOUS_PAPERS_BUTTON:"SET_PREVIOUS_PAPERS_BUTTON",

    SET_RECCOMENDED_BUTTON:"SET_RECCOMENDED_BUTTON",
    SET_ELECTRONICS_BUTTON:"SET_ELECTRONICS_BUTTON",
    SET_PHONES_BUTTON:"SET_PHONES_BUTTON",
    SET_HOME_BUTTON:"SET_HOME_BUTTON",
    SET_CLOTHING_BUTTON:"SET_CLOTHING_BUTTON",




    SEARCH_ALL_PRODUCTS: "SEARCH_ALL_PRODUCTS",
    SEARCH_STATIONERY: "SEARCH_STATIONERY",
    SEARCH_NOTES:"SEARCH_NOTES",
    SEARCH_PREVIOUS_PAPERS:"SEARCH_PREVIOUS_PAPERS",
    SEARCH_ENOTES:"SEARCH_ENOTES",
    BOOK_PRODUCT:"BOOK_PRODUCT",

    SET_AVAILABLE_PRODUCTS:"SET_AVAILABLE_PRODUCTS",
    SET_BOOKED_PRODUCTS:"SET_BOOKED_PRODUCTS",
    SET_TRANSACTION_HISTORY:"SET_TRANSACTION_HISTORY",


    SET_ELECTRONICS:"SET_ELECTRONICS",
    SET_PHONES:"SET_PHONES",
    SET_HOME:"SET_HOME",
    SET_CLOTHING: "SET_CLOTHING",
    SET_RECCOMENDED:"SET_RECCOMENDED",

    SEARCH_RECCOMENDED:"SEARCH_RECCOMENDED",
    SEARCH_ELECTRONICS:"SEARCH_ELECTRONICS",
    SEARCH_PHONES:"SEARCH_PHONES",
    SEARCH_HOME:"SEARCH_HOME",
    SEARCH_CLOTHING:"SEARCH_CLOTHING",


    DELETE_PRODUCT:"DELETE_PRODUCT",
}